package seedu.address.model.util;

import static seedu.address.logic.commands.PhotoCommand.DEFAULT_PHOTO_PATH;

import java.util.HashSet;
import java.util.Set;

import seedu.address.commons.exceptions.IllegalValueException;
import seedu.address.model.AddressBook;
import seedu.address.model.ReadOnlyAddressBook;
import seedu.address.model.person.Address;
import seedu.address.model.person.Birthday;
import seedu.address.model.person.Email;
import seedu.address.model.person.Gender;
import seedu.address.model.person.MatricNo;
import seedu.address.model.person.Name;
import seedu.address.model.person.Person;
import seedu.address.model.person.Phone;
import seedu.address.model.person.PhotoPath;
import seedu.address.model.person.Remark;
import seedu.address.model.person.exceptions.DuplicatePersonException;
import seedu.address.model.person.timetable.Timetable;
import seedu.address.model.tag.Tag;

/**
 * Contains utility methods for populating {@code AddressBook} with sample data.
 */
public class SampleDataUtil {
    public static Person[] getSamplePersons() {
        try {
            return new Person[]{
                new Person(new Name("Labayna Neil Brian Narido"), new Gender("Male"), new MatricNo("A0155006R"),
                        new Phone("96474278"), new Email("neilbrian.nl@gmail.com"),
                        new Address("Blk 630, Yishun St 61"), new Timetable("http://modsn.us/VLQ3g"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH), getTagSet("CS2101", "CS2103T"),
                        new Birthday("02101995")),
                new Person(new Name("Fan Yuting"), new Gender("Female"), new MatricNo("A0162531F"),
                        new Phone("96855667"), new Email("fyt0616@gmail.com"),
                        new Address("Prince George Park Residences NUS"),
                        new Timetable("http://modsn.us/aHN0q"),
                        new Remark("[Likes playing Dota 2]"), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("CS2105", "CS2101", "CS2103T"), new Birthday("16061998")),
                new Person(new Name("Tsai Yu Hsuan"), new Gender("Female"), new MatricNo("A0163331N"),
                        new Phone("95569202"), new Email("cindy93@gmail.com"),
                        new Address("7 Serangoon Avenue 2, #13-07"),
                        new Timetable("http://modsn.us/VLQ3g"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH), getTagSet("CS2101", "CS2103T"),
                        new Birthday("18081993")),
                new Person(new Name("Zachary Tang"), new Gender("Male"), new MatricNo("A0133788N"),
                        new Phone("91676489"), new Email("zachtang@gmail.com"),
                        new Address("Blk 43 Marine Crescent, #24-02"),
                        new Timetable("http://modsn.us/9UKRW"),
                        new Remark("[Can't drink coffee]"), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("CS2101", "CS2103T"), new Birthday("06121995")),
                new Person(new Name("Isabel Tan"), new Gender("Female"), new MatricNo("A0466707R"),
                        new Phone("92492021"), new Email("isabel.tan@gmail.com"),
                        new Address("Blk 47 Tampines Street 20, #17-35"), new Timetable("http://modsn.us/9UKRW"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH), getTagSet("ComputingClub"),
                        new Birthday("07121998")),
                new Person(new Name("Thomas Spencer"), new Gender("Male"), new MatricNo("A0155531K"),
                        new Phone("92624417"), new Email("royb@example.com"),
                        new Address("RC4 NUS UTown"), new Timetable("http://modsn.us/0ECRP"),
                        new Remark("[From London]"), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("ExchangeStudent", "Business"), new Birthday("05111998")),
                new Person(new Name("Bobby Chin"), new Gender("Male"), new MatricNo("A0177348L"),
                        new Phone("99635723"), new Email("chinnybob@gmail.com"),
                        new Address("Blk 320, Ang Mo Kio St 32"), new Timetable("http://modsn.us/9UKRW"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "Sociology"), new Birthday("01101994")),
                new Person(new Name("Buena Pflug"), new Gender("Male"), new MatricNo("A4467880N"),
                        new Phone("99049128"), new Email("buenapflug@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable("http://modsn.us/GWp3V"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "MA1330"), new Birthday("20041996")),
                new Person(new Name("Marlin Nathaniel"), new Gender("Male"), new MatricNo("A3481535O"),
                        new Phone("98344997"), new Email("marlinnathaniel@example.com"),
                        new Address("Blk 21 Hougang Street 80, #14-25"), new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "NUSSU"), new Birthday("25011994")),
                new Person(new Name("Madalene Mcphearson"), new Gender("Male"), new MatricNo("A1796495R"),
                        new Phone("91720552"), new Email("madalenemcphearson@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"),
                        new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "NUSSU"), new Birthday("15041991")),
                new Person(new Name("Kathline Guida"), new Gender("Female"), new MatricNo("A3285865D"),
                        new Phone("92552370"), new Email("kathlineguida@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"),
                        new Timetable("http://modsn.us/rBmlH"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("20101992")),
                new Person(new Name("Young Marley"), new Gender("Female"), new MatricNo("A8571220C"),
                        new Phone("95314096"), new Email("youngmarley@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1101R"), new Birthday("15061993")),
                new Person(new Name("Barbar Messineo"), new Gender("Female"), new MatricNo("A3981800L"),
                        new Phone("99284431"), new Email("barbarmessineo@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable("http://modsn.us/Oqiyc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "MA1101R"), new Birthday("15061993")),
                new Person(new Name("Lucilla Awong"), new Gender("Male"), new MatricNo("A2256727R"),
                        new Phone("94572019"), new Email("lucillaawong@example.com"),
                        new Address("Blk 122 Aljunied Lane, #04-26"), new Timetable("http://modsn.us/FX3uR"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1330"), new Birthday("20031992")),
                new Person(new Name("Tai Yeung"), new Gender("Female"), new MatricNo("A2796193O"),
                        new Phone("96492016"), new Email("taiyeung@example.com"),
                        new Address("41 Buangkok Walk"), new Timetable("http://modsn.us/rBmlH"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "CS2010"), new Birthday("25101991")),
                new Person(new Name("Migdalia Valencia"), new Gender("Male"), new MatricNo("A5673729W"),
                        new Phone("92644585"), new Email("migdaliavalencia@example.com"),
                        new Address("46 Lavender Crescent"), new Timetable("http://modsn.us/Oqiyc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "MA1101R"), new Birthday("01101994")),
                new Person(new Name("Almeda Abboud"), new Gender("Female"), new MatricNo("A3395772A"),
                        new Phone("93118324"), new Email("almedaabboud@example.com"),
                        new Address("Blk 122 Aljunied Lane, #04-26"), new Timetable("http://modsn.us/Oqiyc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1101R"), new Birthday("20041991")),
                new Person(new Name("Jeannine Dillingham"), new Gender("Female"), new MatricNo("A3423732X"),
                        new Phone("96593876"), new Email("jeanninedillingham@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "MA1101R"), new Birthday("01121996")),
                new Person(new Name("Jule Mcphatter"), new Gender("Male"), new MatricNo("A1681721Q"),
                        new Phone("94288455"), new Email("julemcphatter@example.com"),
                        new Address("Blk 407 Pasir Ris Street 11, #08-21"), new Timetable("http://modsn.us/Oqiyc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "MA1101R"), new Birthday("25061997")),
                new Person(new Name("Ilene Billiot"), new Gender("Male"), new MatricNo("A2794916O"),
                        new Phone("91148432"), new Email("ilenebilliot@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable("http://modsn.us/FX3uR"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "NUSSU"), new Birthday("25101996")),
                new Person(new Name("Cleveland Hem"), new Gender("Female"), new MatricNo("A2382495K"),
                        new Phone("92506214"), new Email("clevelandhem@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/FX3uR"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "Friend"), new Birthday("12121995")),
                new Person(new Name("Daisey Woolsey"), new Gender("Female"), new MatricNo("A2604108A"),
                        new Phone("98161504"), new Email("daiseywoolsey@example.com"),
                        new Address("6 Kallang Lane, #08-15"), new Timetable("http://modsn.us/eFI8C"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "MA1101R"), new Birthday("15101994")),
                new Person(new Name("Nakisha Mcgranahan"), new Gender("Male"), new MatricNo("A8108437G"),
                        new Phone("93869295"), new Email("nakishamcgranahan@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable("http://modsn.us/FX3uR"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "CS3216"), new Birthday("01011995")),
                new Person(new Name("Joella Render"), new Gender("Female"), new MatricNo("A8911079N"),
                        new Phone("95476330"), new Email("joellarender@example.com"),
                        new Address("Blk 122 Aljunied Lane, #04-26"), new Timetable("http://modsn.us/HRWvw"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("01041996")),
                new Person(new Name("Contessa Purvines"), new Gender("Male"), new MatricNo("A6494690O"),
                        new Phone("91126176"), new Email("contessapurvines@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/lmOAn"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "ComputingClub"), new Birthday("12101993")),
                new Person(new Name("Sonia Asay"), new Gender("Male"), new MatricNo("A9265842R"),
                        new Phone("97426776"), new Email("soniaasay@example.com"),
                        new Address("Blk 21 Hougang Street 80, #14-25"), new Timetable("http://modsn.us/rBmlH"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1330"), new Birthday("15041994")),
                new Person(new Name("Cecily Dumais"), new Gender("Female"), new MatricNo("A3861852I"),
                        new Phone("96593020"), new Email("cecilydumais@example.com"),
                        new Address("Blk 209 Lorong 1 Dunearn, #10-16"), new Timetable("http://modsn.us/a4iT5"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "MA1330"), new Birthday("15101997")),
                new Person(new Name("Janice Akridge"), new Gender("Male"), new MatricNo("A7825958E"),
                        new Phone("93465813"), new Email("janiceakridge@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable("http://modsn.us/eFI8C"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "Friend"), new Birthday("25051994")),
                new Person(new Name("Columbus Womack"), new Gender("Female"), new MatricNo("A1714495V"),
                        new Phone("99675761"), new Email("columbuswomack@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"),
                        new Timetable("http://modsn.us/GWp3V"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "MA1101R"), new Birthday("15011996")),
                new Person(new Name("Shaniqua Glasgow"), new Gender("Female"), new MatricNo("A1322182I"),
                        new Phone("99532475"), new Email("shaniquaglasgow@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("20061997")),
                new Person(new Name("Faviola Barbera"), new Gender("Male"), new MatricNo("A5079792T"),
                        new Phone("97294233"), new Email("faviolabarbera@example.com"),
                        new Address("Blk 122 Aljunied Lane, #04-26"), new Timetable("http://modsn.us/HRWvw"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1101R"), new Birthday("20101997")),
                new Person(new Name("Carey Kyger"), new Gender("Male"), new MatricNo("A3015813F"),
                        new Phone("94508396"), new Email("careykyger@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"),
                        new Timetable("http://modsn.us/Oqiyc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "CS3216"), new Birthday("01041991")),
                new Person(new Name("Rudolf Mcdougall"), new Gender("Female"), new MatricNo("A4083516X"),
                        new Phone("98748829"), new Email("rudolfmcdougall@example.com"),
                        new Address("46 Lavender Crescent"), new Timetable("http://modsn.us/HRWvw"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1101R"), new Birthday("12101995")),
                new Person(new Name("Marina Morlan"), new Gender("Female"), new MatricNo("A8884675P"),
                        new Phone("92472722"), new Email("marinamorlan@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable("http://modsn.us/qSFsb"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "NUSSU"), new Birthday("15051995")),
                new Person(new Name("Laurette Langlinais"), new Gender("Female"), new MatricNo("A7154509Y"),
                        new Phone("93058308"), new Email("laurettelanglinais@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/HRWvw"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "CS2010"), new Birthday("12101995")),
                new Person(new Name("Devora Brundige"), new Gender("Male"), new MatricNo("A4844221F"),
                        new Phone("91421108"), new Email("devorabrundige@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable("http://modsn.us/lmOAn"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("25121993")),
                new Person(new Name("Luther Hollabaugh"), new Gender("Female"), new MatricNo("A6151233W"),
                        new Phone("91165141"), new Email("lutherhollabaugh@example.com"),
                        new Address("Blk 21 Hougang Street 80, #14-25"), new Timetable("http://modsn.us/Oqiyc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "CS3216"), new Birthday("12031993")),
                new Person(new Name("Letha Fletcher"), new Gender("Female"), new MatricNo("A6266517W"),
                        new Phone("91694797"), new Email("lethafletcher@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/GWp3V"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "ComputingClub"), new Birthday("12051997")),
                new Person(new Name("Chaya Mcgrail"), new Gender("Female"), new MatricNo("A6967900X"),
                        new Phone("91599096"), new Email("chayamcgrail@example.com"),
                        new Address("Blk 209 Lorong 1 Dunearn, #10-16"), new Timetable("http://modsn.us/eFI8C"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "NUSSU"), new Birthday("01061994")),
                new Person(new Name("Gilberto Docherty"), new Gender("Female"), new MatricNo("A9161021N"),
                        new Phone("94315525"), new Email("gilbertodocherty@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable("http://modsn.us/a4iT5"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "CS2010"), new Birthday("01051997")),
                new Person(new Name("Dottie Pillai"), new Gender("Male"), new MatricNo("A9814802W"),
                        new Phone("96016868"), new Email("dottiepillai@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/a4iT5"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "Friend"), new Birthday("12011992")),
                new Person(new Name("Alexa Wolf"), new Gender("Male"), new MatricNo("A8025285U"),
                        new Phone("98645631"), new Email("alexawolf@example.com"),
                        new Address("Blk 209 Lorong 1 Dunearn, #10-16"), new Timetable("http://modsn.us/qSFsb"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1101R"), new Birthday("25101996")),
                new Person(new Name("Rosana Kyer"), new Gender("Male"), new MatricNo("A1777501A"),
                        new Phone("92829610"), new Email("rosanakyer@example.com"),
                        new Address("41 Buangkok Walk"), new Timetable("http://modsn.us/a4iT5"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("25101994")),
                new Person(new Name("Cherelle Hayman"), new Gender("Male"), new MatricNo("A3483409O"),
                        new Phone("98035569"), new Email("cherellehayman@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"),
                        new Timetable("http://modsn.us/rBmlH"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "Friend"), new Birthday("15011992")),
                new Person(new Name("Rheba Gosnell"), new Gender("Male"), new MatricNo("A5915667K"),
                        new Phone("99682217"), new Email("rhebagosnell@example.com"),
                        new Address("46 Lavender Crescent"), new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "NUSSU"), new Birthday("15101991")),
                new Person(new Name("Earl Vick"), new Gender("Male"), new MatricNo("A8981194S"),
                        new Phone("98669157"), new Email("earlvick@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "MA1101R"), new Birthday("01051992")),
                new Person(new Name("Madelene Gregerson"), new Gender("Male"), new MatricNo("A7638739V"),
                        new Phone("98583669"), new Email("madelenegregerson@example.com"),
                        new Address("Blk 21 Hougang Street 80, #14-25"), new Timetable("http://modsn.us/qSFsb"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "NUSSU"), new Birthday("25061992")),
                new Person(new Name("Charla Running"), new Gender("Male"), new MatricNo("A2191414G"),
                        new Phone("92185363"), new Email("charlarunning@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable("http://modsn.us/GWp3V"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "MA1330"), new Birthday("15101993")),
                new Person(new Name("Verda Whitlatch"), new Gender("Male"), new MatricNo("A9864961P"),
                        new Phone("94947838"), new Email("verdawhitlatch@example.com"),
                        new Address("Blk 407 Pasir Ris Street 11, #08-21"), new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "NUSSU"), new Birthday("12041991")),
                new Person(new Name("Merrilee Schwenk"), new Gender("Female"), new MatricNo("A4810334U"),
                        new Phone("92724879"), new Email("merrileeschwenk@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable("http://modsn.us/rBmlH"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "Friend"), new Birthday("15101991")),
                new Person(new Name("Lakeshia Petree"), new Gender("Female"), new MatricNo("A5985393I"),
                        new Phone("99962101"), new Email("lakeshiapetree@example.com"),
                        new Address("Blk 209 Lorong 1 Dunearn, #10-16"), new Timetable("http://modsn.us/GWp3V"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "MA1101R"), new Birthday("20031995")),
                new Person(new Name("Sheba Galang"), new Gender("Female"), new MatricNo("A1005103S"),
                        new Phone("95717898"), new Email("shebagalang@example.com"),
                        new Address("46 Lavender Crescent"), new Timetable("http://modsn.us/qSFsb"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1101R"), new Birthday("01051992")),
                new Person(new Name("Victor Amsden"), new Gender("Female"), new MatricNo("A6053968N"),
                        new Phone("92308943"), new Email("victoramsden@example.com"),
                        new Address("6 Kallang Lane, #08-15"), new Timetable("http://modsn.us/FX3uR"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "MA1330"), new Birthday("12121996")),
                new Person(new Name("Ka Logan"), new Gender("Male"), new MatricNo("A9167973W"),
                        new Phone("96095275"), new Email("kalogan@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable("http://modsn.us/eFI8C"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Computing", "CS2010"), new Birthday("01051995")),
                new Person(new Name("Wendi Fabre"), new Gender("Female"), new MatricNo("A3783741S"),
                        new Phone("99849159"), new Email("wendifabre@example.com"),
                        new Address("46 Lavender Crescent"), new Timetable("http://modsn.us/HOhl3"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "NUSSU"), new Birthday("01011995")),
                new Person(new Name("Monika Bence"), new Gender("Female"), new MatricNo("A2883370S"),
                        new Phone("97211978"), new Email("monikabence@example.com"),
                        new Address("Blk 122 Aljunied Lane, #04-26"), new Timetable("http://modsn.us/FX3uR"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1101R"), new Birthday("25031997")),
                new Person(new Name("Grazyna Greaney"), new Gender("Male"), new MatricNo("A5862673P"),
                        new Phone("94127350"), new Email("grazynagreaney@example.com"),
                        new Address("Blk 21 Hougang Street 80, #14-25"), new Timetable("http://modsn.us/AWYIc"),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "CS2010"), new Birthday("25021993")),
            };
        } catch (IllegalValueException e) {
            throw new AssertionError("sample data cannot be invalid", e);
        }
    }

    public static ReadOnlyAddressBook getSampleAddressBook() {
        try {
            AddressBook sampleAb = new AddressBook();
            for (Person samplePerson : getSamplePersons()) {
                sampleAb.addPerson(samplePerson);
            }
            return sampleAb;
        } catch (DuplicatePersonException e) {
            throw new AssertionError("sample data cannot contain duplicate persons", e);
        }
    }

    /**
     * Returns a tag set containing the list of strings given.
     */
    public static Set<Tag> getTagSet(String... strings) throws IllegalValueException {
        HashSet<Tag> tags = new HashSet<>();
        for (String s : strings) {
            tags.add(new Tag(s));
        }
        return tags;
    }
}
